### ISSUE TITLE
User CRUD

### ISSUE THREAD

**Issue by bingoogolapple** [bingoogolapple/SpringBootNote#2]
> application.yml

```
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springbootnote
    username: root
    password: 12345678
  jpa:
    hibernate:
      # create 先删除,再重新创建
      # update 第一次运行时创建,再次运行时不会删除再重新创建,如果有修改则修改
      # create-drop 运行时创建,停止运行时删除
      # none 什么都不做
      # validate 验证类里面的属性和表结构是否一致,如果不一致的话就会报错
      ddl-auto: update
    show-sql: true # 显示 sql 语句
```
